name: Validar HTML con W3C Validator

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Validar HTML con W3C Validator
        uses: validator/validator@20.6.30
        with:
          file: "banco.html,seguros.html"
