name: Validar HTML con W3C
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Validar HTML con W3C
        uses: w3c/validate-action@v1
        with:
          root: .
          level: error
          validator: "https://validator.w3.org/nu/"
