name: Validar HTML con W3C

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Validar HTML con W3C
      uses: validator/validator@v1
      with:
        files: '*.html'
