name: Validar HTML con W3C

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validar HTML
      uses: validator/validator@v20.6.30
      with:
        files: '*.html'
